import type { Metadata } from "next";
import "../../styles/globals.css";
import { ProdNavBar } from "../testing/ProdNavBar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className= 'flex justify-center'>
        <main>
          < ProdNavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
