import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./components/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <body className="flex flex-col min-h-screen">

        <header className="bg-[#18181b] text-white p-4 text-center">
          <Navigation/>
        </header>

        <main className="flex-grow">
          {children}
        </main>
        
        <footer className="bg-[#18181b] text-white p-4 text-center">
            PGC
        </footer>
      </body>
    </html>
  );
}
